pub const DUMMY_TOKEN: &str = "Bearer ZHVtbXlfdG9rZW4=";
pub const ENGINE_URL: &str = "http://localhost:10560";

pub fn get_valid_process_definition_xml() -> String {
    let rand_id = uuid::Uuid::new_v4().to_string();
    let xml = format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?> <bpmn:definitions xmlns:bpmn=\"http://www.omg.org/spec/BPMN/20100524/MODEL\" xmlns:bpmndi=\"http://www.omg.org/spec/BPMN/20100524/DI\" xmlns:dc=\"http://www.omg.org/spec/DD/20100524/DC\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:di=\"http://www.omg.org/spec/DD/20100524/DI\" id=\"{}\" targetNamespace=\"http://bpmn.io/schema/bpmn\" exporter=\"5Minds Studio\" exporterVersion=\"1\"> <bpmn:collaboration id=\"{}\" name=\"\"> <bpmn:participant id=\"{}\" name=\"{}\" processRef=\"{}\" /> </bpmn:collaboration> <bpmn:process id=\"{}\" name=\"{}\" isExecutable=\"true\"> <bpmn:laneSet> <bpmn:lane id=\"Lane_1xzf0d3\" name=\"Bar Lane\"> <bpmn:flowNodeRef>StartEvent_1</bpmn:flowNodeRef> <bpmn:flowNodeRef>Event_1lpuf0o</bpmn:flowNodeRef> </bpmn:lane> </bpmn:laneSet> <bpmn:startEvent id=\"StartEvent_1\" name=\"Start\"> <bpmn:outgoing>Flow_1t9bzyi</bpmn:outgoing> </bpmn:startEvent> <bpmn:sequenceFlow id=\"Flow_1t9bzyi\" sourceRef=\"StartEvent_1\" targetRef=\"Event_1lpuf0o\" /> <bpmn:endEvent id=\"Event_1lpuf0o\" name=\"End\"> <bpmn:incoming>Flow_1t9bzyi</bpmn:incoming> </bpmn:endEvent> </bpmn:process> <bpmndi:BPMNDiagram id=\"BPMNDiagram_1\"> <bpmndi:BPMNPlane id=\"BPMNPlane_1\" bpmnElement=\"Collaboration_1cidyxu\"> <bpmndi:BPMNShape id=\"Participant_0px403d_di\" bpmnElement=\"Participant_0px403d\" isHorizontal=\"true\"> <dc:Bounds x=\"5\" y=\"100\" width=\"335\" height=\"150\" /> <bpmndi:BPMNLabel /> </bpmndi:BPMNShape> <bpmndi:BPMNShape id=\"Lane_1xzf0d3_di\" bpmnElement=\"Lane_1xzf0d3\" isHorizontal=\"true\"> <dc:Bounds x=\"35\" y=\"100\" width=\"305\" height=\"150\" /> <bpmndi:BPMNLabel /> </bpmndi:BPMNShape> <bpmndi:BPMNShape id=\"StartEvent_1_di\" bpmnElement=\"StartEvent_1\"> <dc:Bounds x=\"92\" y=\"152\" width=\"36\" height=\"36\" /> <bpmndi:BPMNLabel> <dc:Bounds x=\"98\" y=\"195\" width=\"24\" height=\"14\" /> </bpmndi:BPMNLabel> </bpmndi:BPMNShape> <bpmndi:BPMNShape id=\"Event_1lpuf0o_di\" bpmnElement=\"Event_1lpuf0o\"> <dc:Bounds x=\"252\" y=\"152\" width=\"36\" height=\"36\" /> <bpmndi:BPMNLabel> <dc:Bounds x=\"260\" y=\"195\" width=\"20\" height=\"14\" /> </bpmndi:BPMNLabel> </bpmndi:BPMNShape> <bpmndi:BPMNEdge id=\"Flow_1t9bzyi_di\" bpmnElement=\"Flow_1t9bzyi\"> <di:waypoint x=\"128\" y=\"170\" /> <di:waypoint x=\"252\" y=\"170\" /> </bpmndi:BPMNEdge> </bpmndi:BPMNPlane> </bpmndi:BPMNDiagram> </bpmn:definitions>", 
        rand_id, rand_id, rand_id, rand_id, rand_id, rand_id, rand_id
    );

    xml
}
