name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          sudo apt-get update
          sudo apt-get install -y rustc cargo

      - name: Build project
        run: cargo build --release --all-targets --verbose

      - name: Stash build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: target/release

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Start 5Minds ProcessCube Engine
        run: docker run --name processcube_engine -d -p 10560:80 5minds/processcube_engine:16.0.0

      - name: Install Rust
        run: |
          sudo apt-get update
          sudo apt-get install -y rustc cargo

      - name: Restore build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Run tests
        run: cargo test --all --verbose

      - name: Show 5Minds Engine logs if tests failed
        if: ${{ job.status == 'failure' }}
        run: docker logs processcube_engine

      - name: Stop 5Minds Engine
        run: |
          docker stop processcube_engine
          docker rm processcube_engine

  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          sudo apt-get update
          sudo apt-get install -y rustc cargo

      - name: Restore build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
