name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build_test_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start ProcessCube® Engine
        run: docker run --name processcube_engine -d -p 10560:80 5minds/processcube_engine:16.0.0

      - name: Install Rust
        run: |
          sudo apt-get update
          sudo apt-get install -y rustc cargo

      - name: Build project
        run: cargo build --release --all-targets --verbose

      - name: Run tests
        run: cargo test --all --verbose

      - name: Show ProcessCube® Engine logs if tests failed
        if: ${{ job.status == 'failure' }}
        run: docker logs processcube_engine

      - name: Stop ProcessCube® Engine
        run: |
          docker stop processcube_engine
          docker rm processcube_engine

      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
